---
# Debian Wheezy with Apache 2.2 and PHP 5.6 FPM

- name: Update apt cache
  apt: update_cache=yes cache_valid_time=86400

- name: Install libapache2-mod-fastcgi
  apt: pkg=libapache2-mod-fastcgi state=present force=yes

- name: Enable apache2 actions and fastcgi module
  apache2_module: state=present name={{ item }}
  with_items:
    - actions
    - fastcgi
  notify: restart apache2

- name: Put new fastcgi.conf into /etc/apache2/mods-available/
  template:
    src: fastcgi.conf.j2
    dest: "/etc/apache2/mods-available/fastcgi.conf"
    owner: root
    group: root
    mode: u+rw,go+r
  notify: restart apache2
